<?php

/**
 * @file
 * Support for configurable user profiles.
 */

use Drupal\user\UserInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Component\Utility\String;
use Drupal\Core\Url;
use Drupal\entity\Entity\EntityFormDisplay;
use Drupal\profile\Entity\ProfileType;
use Drupal\field\FieldInstanceConfigInterface;

/**
 * Implements hook_help().
 */
function profile_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.profile':
//      @todo:
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Profile module provides a fieldable entity.') . '</p>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Types of profiles') . '</dt>';
      $output .= '<dd>' . t('TODO:.') . '</dd>';
      $output .= '<dt>' . t('Creating profiles') . '</dt>';
      $output .= '<dd>' . t('TODO:.') . '</dd>';
      $output .= '</dl>';
      return $output;
  }
}

/**
 * Implements hook_permission().
 */
function profile_permission() {
  $permissions = array(
    'administer profile types' => array(
      'title' => t('Administer profile types'),
      'restrict access' => TRUE,
    ),
    'bypass profile access' => array(
      'title' => t('Bypass profile access'),
      'description' => t('View and edit all user profiles, including private field values.'),
      'restrict access' => TRUE,
    ),
  );

  foreach (ProfileType::loadMultiple() as $profile_type) {
    $bundle = $profile_type->id();
    $type = $profile_type->label();
    $permissions += array(
      "add own $bundle profile" => array(
        'title' => t('%type: Add own profile', array('%type' => $type)),
      ),
      "add any $bundle profile" => array(
        'title' => t('%type: Add any profile', array('%type' => $type)),
      ),
      "view own $bundle profile" => array(
        'title' => t('%type: View own profile', array('%type' => $type)),
      ),
      "view any $bundle profile" => array(
        'title' => t('%type: View any profile', array('%type' => $type)),
      ),
      "edit own $bundle profile" => array(
        'title' => t('%type: Edit own profile', array('%type' => $type)),
      ),
      "edit any $bundle profile" => array(
        'title' => t('%type: Edit any profile', array('%type' => $type)),
      ),
      "delete own $bundle profile" => array(
        'title' => t('%type: Delete own profile', array('%type' => $type)),
      ),
      "delete any $bundle profile" => array(
        'title' => t('%type: Delete any profile', array('%type' => $type)),
      ),
    );
  }
  return $permissions;
}

/**
 * Implements hook_user_view().
 */
/**
 * Implements hook_user_view().
 */
function profile_user_view(array &$build, UserInterface $account, EntityViewDisplayInterface $display, $view_mode, $langcode) {
  // Only attach profiles for the full account view.
  if ($view_mode != 'full') {
    return;
  }
  // Position profiles at the bottom of account page.
  $weight = 100;
  foreach (\Drupal::configFactory()
             ->listAll('profile.type.') as $config_name) {
    $config = \Drupal::config($config_name);

    $profiles = \Drupal::entityManager()->getStorage('profile')->loadByProperties(array(
      'uid' => $account->id(),
      'type' => $config->get('id')));

    if (count($profiles)) {
      $build['profiles']['#weight'] = $weight + $config->get('weight');
      $build['profiles'][$config->get('id')] = array(
        '#theme' => 'profile_items',
        '#profile_items' => $profiles,
        '#type' => $config->get('label'),
      );
    }
  }
  $build['#attached']['library'][] = 'profile/drupal.profile-items';
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add available profile forms to the user registration form.
 *
 */
function profile_form_user_register_form_alter(&$form, &$form_state) {
  $attached_profile_form = FALSE;
  $weight = 90;
  foreach (\Drupal::configFactory()
             ->listAll('profile.type.') as $config_name) {
    $config = \Drupal::config($config_name);

    $profile_type = ProfileType::load($config->get('id'));

    $instances = array_filter(\Drupal::entityManager()
      ->getFieldDefinitions('profile', $config->get('id')), function ($field_definition) {
      return $field_definition instanceof FieldInstanceConfigInterface;
    });

    if ($profile_type->registration === TRUE && count($instances)) {
      $id = $profile_type->id();
      if (empty($form_state['profiles'][$id])) {
        $entity = entity_create('profile', array(
          'type' => $id,
          'langcode' => $profile_type->language() ? $profile_type->language() : \Drupal::languageManager()
            ->getDefaultLanguage()->id
        ));
        // Attach profile entity form.
        $form_state['profiles'][$id] = $entity;
        $form_state['form_display_' . $id] = EntityFormDisplay::collectRenderDisplay($entity, 'default');
        $form['entity_' . $id] = array(
          '#type' => 'details',
          '#title' => $profile_type->label(),
          '#tree' => TRUE,
          '#parents' => array('entity_' . $id),
          '#weight' => ++$weight,
          '#open' => TRUE,
        );
        $form_state['form_display_' . $id]->buildForm($entity, $form['entity_' . $id], $form_state);

        $attached_profile_form = TRUE;
      }
    }
  }
  if ($attached_profile_form) {
    $form['actions']['submit']['#validate'][] = 'profile_form_user_register_form_validate';
    $form['actions']['submit']['#submit'][] = 'profile_form_user_register_form_submit';
  }
}

/**
 * Extra form validation handler for the user registration form.
 */
function profile_form_user_register_form_validate(array &$form, array &$form_state) {
  foreach ($form_state['profiles'] as $bundle => $entity) {
    $form_display = $form_state['form_display_' . $bundle];
    $form_display->extractFormValues($entity, $form['entity_' . $bundle], $form_state);
    $form_display->validateFormValues($entity, $form['entity_' . $bundle], $form_state);
  }
}

/**
 * Extra form submission handler for the user registration form.
 */
function profile_form_user_register_form_submit(array &$form, array &$form_state) {
  $account = $form_state['controller']->getEntity();
  foreach ($form_state['profiles'] as $bundle => $entity) {
    $entity->setOwnerId($account->id());
    $entity->save();
  }
}

/**
 * Implements hook_theme().
 */
function profile_theme() {
  return array(
    'profile_items' => array(
      'variables' => array('profile_items' => NULL, 'type' => NULL),
      'template' => 'profile-items',
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK() for profile templates.
 */
function template_preprocess_profile_items(&$variables) {
  if (count($variables['profile_items'])) {
    $variables['title'] = String::checkPlain($variables['type']);
    foreach ($variables['profile_items'] as $profile_item) {
      $variables['items'][] = entity_view($profile_item, 'default');
      $variables['edit_links'][] = \Drupal::linkGenerator()
        ->generateFromUrl(t('Edit'), new Url("profile.account_edit_profile", array(
          'user' => \Drupal::currentUser()->id(),
          'type' => $profile_item->bundle(),
          'id' => $profile_item->id(),
        )));
      $variables['delete_links'][] = \Drupal::linkGenerator()
        ->generateFromUrl(t('Delete'), new Url("profile.account_delete_profile", array(
          'user' => \Drupal::currentUser()->id(),
          'type' => $profile_item->bundle(),
          'id' => $profile_item->id(),
        )));
    }
  }
}
